### ISSUE TITLE
Working example for decoding using dbc 

### ISSUE THREAD

**Issue by ezpzbz** [tsabelmann/cantools-rs#1]
Hi @tsabelmann. I'm new to rust and recently found your cantools code. I currently use cantools in python to decode BLF files using dbc. I wonder if you may provide a minimal example of rust code that can do the same using your code?

**Comment by tsabelmann** [comment]
Hi @pzarabadip, I am happy to hear that you want to use cantools-rs. Unfortunately, this project is not yet ready to be used extensively. However, if you want, you can contribute and implement the DBC and BLF file parsers yourself and add them to cantools-rs. So for now I suggest that to keep using the cantools python package. If I can help you with something else, feel free to reach out.

**Comment by ezpzbz** [comment]
Thanks @tsabelmann for quick response. As I'm new to Rust, it might take a while to contribute but certainly it's gonna be on my radar. Cheers.
